plugins {
    id 'com.android.application'
}

android {
    namespace 'com.radiofreccianera.app'
    compileSdk 36

    defaultConfig {
        applicationId 'com.radiofreccianera.app'
        minSdk 26
        targetSdk 36
        versionCode 1
        versionName '1.0.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'com.google.androidbrowserhelper:androidbrowserhelper:2.7.2'
}
